name: custom_social_button
description: A customizable Flutter button widget that displays user-provided SVG icons with customizable size alongside the button title.
version: 1.0.4
homepage: https://github.com/zobayerdev/custom_social_button_package

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
# No assets bundled with the package